### ISSUE TITLE
Tabs der Kommentare- und Inhaltsverzeichnis-Spalten sind nicht sichtbar

### ISSUE THREAD

**Issue by dagraf** [ilub-unibe-ch/InteractiveVideo#1]
**Describe the bug**
Die Titel der beiden Spalten "Kommentare" und "Inhaltsverzeichnis" werden erst sichtbar, wenn man mit der Maus drüber fährt und so ein Hover-Over auslöst. Vorher nicht.

**To Reproduce**
1. Erstelle ein Interaktives Video, das mind. ein Kapitel enthält
2. Wechsle in den Tab "Inhalt"
3. Siehe den Fehler: oberhalb der Kommentar-/Inhaltsverzeichnis-Spalte wird keine Überschrift angezeigt

**Expected behavior**
Die Überschriften sollen auch ohne Hover-Over angezeigt werden. Gerne nach Möglichkeit so gestalten, dass sie wie "Tabs" aussehen. 

**Additional context**
Beispiele findest du hier: https://ilias-next.unibe.ch/goto_ilias3_unibe_fold_2577245.html

**Comment by yvseiler** [comment]
gefixet mit commit https://github.com/ilub-unibe-ch/ILIAS-Skin/commit/34e2c5254777052a676258d3e2160036ec80a7be . Wurde eingespielt auf ilias-next.unibe.ch

Resultat: 
<img width="1138" alt="Bildschirmfoto 2024-07-22 um 15 58 45" src="https://github.com/user-attachments/assets/1cc9be01-d4fd-4608-b2e0-4588a6f1d488">
